# https://thelounge.chat/docs/guides/reverse-proxies
# https://hub.docker.com/r/linuxserver/thelounge/
---
version: "3.7"
services:
  irc-lounge:
    image: linuxserver/thelounge
    container_name: irc-lounge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
#    network_mode: service:vpn-proxy
    networks:
      - traefik
    volumes:
      - ${USERDIR}/irc-lounge:/config
 #   ports:
 #     - "9000:9000"
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik
      traefik.backend: irc-lounge
      traefik.protocol: http
      traefik.port: 9000
      traefik.frontend.rule: Host:irc-lounge.${DOMAINNAME},
      traefik.frontend.auth.forward.address: http://traefik-forward-auth:4181
      traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
      traefik.frontend.auth.forward.trustForwardHeader: "true"
    restart: always

networks:
  traefik:
    name: traefik
