version: "2"
networks:
  traefik:
    name: traefik

services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    hostname: jackett
    networks:
      traefik:
    dns:
      - 192.168.1.1
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: Europe/London
#      RUN_OPTS: run options here #optional
    volumes:
      - /media/tom/Docker/Jackett/config:/config
      - /media/tom/Downloads:/downloads
    ports:
      - 9117:9117
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik
      traefik.backend: jackett
      traefik.protocol: http
      traefik.port: 9117
      traefik.frontend.rule: Host:jackett.${DOMAINNAME},
      traefik.frontend.auth.forward.address: http://traefik-forward-auth:4181
      traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
      traefik.frontend.auth.forward.trustForwardHeader: "true"
      traefik.frontend.headers.SSLForceHost: "true"
      traefik.frontend.headers.SSLHost: jackett.${DOMAINNAME}
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.headers.frameDeny: "true"
      traefik.frontend.headers.customFrameOptionsValue: 'allow-from https:${DOMAINNAME}'
    restart: always
