---
version: "3.7"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    networks:
      traefik:
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
#      RUN_OPTS: run options here #optional
    volumes:
      - ${USERDIR}/jackett:/config
      - /data/downloads:/downloads
    ports:
      - 9117:9117
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik
      traefik.backend: jackett
      traefik.protocol: http
      traefik.port: 9117
      traefik.frontend.rule: Host:jackett.${DOMAINNAME},
      traefik.frontend.auth.forward.address: http://traefik-forward-auth:4181
      traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
      traefik.frontend.auth.forward.trustForwardHeader: "true"
      traefik.frontend.headers.SSLForceHost: "true"
      traefik.frontend.headers.SSLHost: jackett.${DOMAINNAME}, ${DOMAINNAME}
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.headers.frameDeny: "true"
      traefik.frontend.headers.customFrameOptionsValue: 'allow-from https:${DOMAINNAME}'
    restart: unless-stopped

networks:
  traefik:
    name: traefik
