version: '3.7'
networks:
  traefik:
    name: traefik

services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    hostname: lidarr
    networks:
      traefik:
    dns:
      - 192.168.1.1
#    ports:
#      - "8686:8686"
    volumes:
      - ${USERDIR}/lidarr:/config
      - /media:/media
      - ${USERDIR}/sabnzbd/complete:/complete
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      HOME: /config
      TZ: ${TZ}
      UMASK_SET: 022
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: https
      traefik.frontend.rule: Host:lidarr.${DOMAINNAME},
      traefik.port: 8686
      traefik.backend: lidarr
      traefik.docker.network: traefik
      traefik.frontend.headers.SSLHost: lidarr.${DOMAINNAME}, ${DOMAINNAME}
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.headers.frameDeny: "true"
      traefik.frontend.headers.customFrameOptionsValue: 'allow-from https://${DOMAINNAME}'
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.auth.forward.address: http://traefik-forward-auth:4181
      traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
      traefik.frontend.auth.forward.trustForwardHeader: "true"
    restart: always
