
version: '3.7'
networks:
  traefik:
    name: traefik

services:
  hydra:
    image: linuxserver/hydra2
    container_name: hydra2
    hostname: hydra2
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${USERDIR}/hydra2:/config
      - /data/bricks/node6/sabnzbd/completed:/downloads
#    ports:
#      - 5076:5076
    networks:
      traefik:
    restart: always
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik
      traefik.backend: hydra2
      traefik.protocol: http
      traefik.port: 5076
      traefik.frontend.rule: Host:hydra2.${DOMAINNAME}
      traefik.frontend.auth.forward.address: http://traefik-forward-auth:4181
      traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
      traefik.frontend.auth.forward.trustForwardHeader: "true"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.headers.SSLForceHost: "true"
      traefik.frontend.headers.SSLHost: hydra2.${DOMAINNAME}
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.headers.frameDeny: "true"
      traefik.frontend.headers.customFrameOptionsValue: 'allow-from https:${DOMAINNAME}'
    restart: always
