version: "2"
networks:
  traefik:

services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    hostname: sonarr
    networks:
      traefik:
    dns:
      - 192.168.1.1
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      HOME: /config
      TZ: Europe/London
      UMASK_SET: 022
    ports:
      - 8989:8989
    volumes:
      - /media/tom/Docker/Sonarr/config:/config
      - /media/tom/Elements2/Series HD:/media1
      - /media/tom/Elements/Series HD:/media2
      - /media/tom/Docker/Transmission/:/downloads

    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik
      traefik.backend: sonarr
      traefik.protocol: http
      traefik.port: 8989
      traefik.frontend.rule: Host:sonarr.${DOMAINNAME}
      traefik.frontend.auth.basic.users: ${TRAEFIK_BASIC_USER}
      traefik.frontend.auth.forward.address: http://traefik-forward-auth:4181
      traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
      traefik.frontend.auth.forward.trustForwardHeader: "true"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.headers.SSLForceHost: "true"
      traefik.frontend.headers.SSLHost: sonarr.${DOMAINNAME}
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.headers.frameDeny: "true"
      traefik.frontend.headers.customFrameOptionsValue: 'allow-from https:${DOMAINNAME}'
    restart: always
