version: '3.7'

services:
  traefik:
    image: traefik:latest
    command: 
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS TLS.SniStrict:true TLS.MinVersion:VersionTLS12"
      - "--acme"
      - "--defaultentrypoints=http,https"
      - "--acme.storage=/etc/traefik/acme/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.email=user@example.com"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=docker.lan"
      - "--docker.watch"
    environment:
      TZ: America/New_York
#      CLOUDFLARE_EMAIL: user@example.com
#      CLOUDFLARE_API_KEY: gdfgdfsgdfg
      GODADDY_API_SECRET: sdfsdfsdfsdf
      GODADDY_API_KEY: sdfsdfsdfsdf
      PROVIDER: godaddy
    ports:
      - target: 80
        published: 80
#        mode: host
      - target: 443
        published: 443
#        mode: host
      - target: 8080
        published: 8080
#        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /HAfolder/traefik:/etc/traefik
      - /HAfolder/docker/shared:/shared
      - /HAfolder/htpasswd/.htpasswd:/.htpasswd:ro
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 30s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      labels:
        traefik.enable: "false"
        traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
        traefik.frontend.redirect.entryPoint: https
        traefik.frontend.entryPoint: http
        traefik.frontend.rule: Host:traefik.example.com,
        traefik.port: 8080
        traefik.protocol: http
        traefik.frontend.priority: 1
        traefik.backend: traefik
        traefik.docker.network: traefik
        traefik.frontend.headers.SSLRedirect: "true"
        traefik.frontend.headers.STSSeconds: 315360000
        traefik.frontend.headers.browserXSSFilter: "true"
        traefik.frontend.headers.contentTypeNosniff: "true"
        traefik.frontend.headers.forceSTSHeader: "true"
        traefik.frontend.headers.SSLHost: example.com
        traefik.frontend.headers.STSIncludeSubdomains: "true"
        traefik.frontend.headers.STSPreload: "true"
        traefik.frontend.headers.frameDeny: "true"
        traefik.frontend.auth.basic.users: xxx:xxx

networks:
  traefik:
    driver: overlay
    attachable: true
    name: traefik
    external: false
  external:
    driver: bridge
    attachable: true
    name: external
    external: false
