---
version: "3.7"
services:
 irc-lounge:
    image: linuxserver/thelounge
    container_name: irc-lounge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    network_mode: "service:vpn-proxy"
    networks:
      - traefik-net
    volumes:
      - ${USERDIR}/irc-lounge:/config
    ports:
      - "9000:9000"
    restart: always

networks:
  traefik:
    external:
      name: traefik-net
