#
#
# https://hub.docker.com/_/postgres
---
version: "3.7"
services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "8780:8080"
    networks:
      - keycloak
        alias: keycloak
      - traefik
    volumes:
      - ${USERDIR}/keycloak/config:/config
      - ${USERDIR}/keycloak/config.json:/config.json
      - /etc/localtime:/etc/localtime:ro
    environment:
#      - PUID=1000
#      - PGID=1000
      - KEYCLOAK_USER=${KEYCLOAKUSER}
      - KEYCLOAK_PASSWORD=${KEYCLOAKPASS}
      - KEYCLOAK_IMPORT=/config.json
      - DB_VENDOR=postgres
      - DB_DATABASE=keycloak
      - DB_ADDR=keycloak-db
      - DB_USER=keycloak
      - DB_PASSWORD=myuberpassword
# This is required to run keycloak behind traefik
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_HOSTNAME=keycloak.${DOMAINNAME}
# Tell Postgress what user/password to create
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=myuberpassword
    labels:
      - traefik.frontend.rule=Host:keycloak.${DOMAINNAME}
      - traefik.port=8080
      - traefik.docker.network=traefik

  keycloak-db:
#    env_file: /var/data/config/keycloak/keycloak.env
    image: postgres
    volumes:
      - ${USERDIR}/keycloak/database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro    
    environmemt:
      - DB_VENDOR=postgres
      - DB_DATABASE=keycloak
      - DB_ADDR=keycloak-db
      - DB_USER=keycloak
      - DB_PASSWORD=myuberpassword
# This is required to run keycloak behind traefik
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_HOSTNAME=keycloak.${DOMAINNAME}
# Tell Postgress what user/password to create
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=myuberpassword
    networks:
      - keycloak
        alias: keycloak-db

  keycloak-db-backup:
    image: postgres
#    env_file: /var/data/config/keycloak/keycloak-backup.env
    volumes:
      - /var/data/keycloak/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGHOST=keycloak-db
      - PGUSER=keycloak
      - PGPASSWORD=myuberpassword
      - BACKUP_NUM_KEEP=7
      - BACKUP_FREQUENCY=1d
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        pg_dump -Fc > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.psql
        (ls -t /dump/dump*.psql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.psql)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    networks:
      - keycloak
        alias: keycloak-db-backup
          
networks:
  keycloak:
    name: keycloak
  traefik:
    name: traefik
