# https://wiki.archlinux.org/index.php/RTorrent
# https://github.com/rakshasa/rtorrent/wiki/CONFIG-Template
# https://rtorrent-docs.readthedocs.io/en/latest/cookbook.html#config-template-deconstructed
---
version: "3.7"
services:
  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
# not needed?
#    cap_add:
#      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    networks:
      - traefik-net
      - rutorrent
    volumes:
      - ${USERDIR}/rutorrent/config:/config
      - ${USERDIR}/rutorrent/downloads:/downloads
    ports:
      - 80:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: always

networks:
  rutorrent:
    name: rutorrent
  traefik:
    external:
      name: traefik-net
