# https://wiki.archlinux.org/index.php/RTorrent
# https://github.com/rakshasa/rtorrent/wiki/CONFIG-Template
# https://rtorrent-docs.readthedocs.io/en/latest/cookbook.html#config-template-deconstructed
# http://<host>:9080/
# https://<host>:9443/
# Username:- admin Password:- rutorrent
---
version: "3.7"
services:
  vpn-rutorrent:
    image: binhex/arch-rtorrentvpn
    container_name: vpn-rutorrent
    cap_add:
      - NET_ADMIN
    ports:
      - "9080:9080"
      - "9443:9443"
      - "8118:8118"
    networks:
      - vpn-rutorrent
    volumes:
      - ${USERDIR}/vpn-rutorrent/data:/data
      - ${USERDIR}/vpn-rutorrent/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000 #Might need to be 0, run id inside container
      - PGID=1000 #Might need to be 0
      - PHP_TZ=<php>
      - VPN_ENABLED=yes
      - VPN_USER=${VPNUSER}
      - VPN_PASS=${VPNPASS}
      - VPN_PROV=pia #airvpn|custom
      - VPN_OPTIONS=#additional openvpn cli options
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - ENABLE_AUTODL_IRSSI=<yes|no>
      - ENABLE_RPC2=<yes|no>
      - ENABLE_RPC2_AUTH=<yes|no>
#Use specific NS for each VPN service to prevent DNS leakage
      - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1
      - DEBUG=false
      - UMASK=000

networks:
  vpn-rutorrent:
    name: vpn-rutorrent
